### **Importing Library**

In [1]:
# Importing libraries
!pip install --upgrade kneed

import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, silhouette_score
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import tree
from kneed import KneeLocator
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [2]:
# dataset
url = "https://raw.githubusercontent.com/isnanmulia/lecture-datasets/main/mobileprice_modified.csv"
data = pd.read_csv(url)
print(data)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0             842.0     0          2.2         0   1       0         7.0   
1            1021.0     1          0.5         1   0       1        53.0   
2             563.0     1          0.5         1   2       1        41.0   
3             615.0     1          2.5         0   0       0        10.0   
4            1821.0     1          1.2         0  13       1        44.0   
...             ...   ...          ...       ...  ..     ...         ...   
1995          794.0     1          0.5         1   0       1         2.0   
1996         1965.0     1          2.6         1   0       0        39.0   
1997         1911.0     0          0.9         1   1       1        36.0   
1998         1512.0     0          0.9         0   4       1        46.0   
1999          510.0     1          2.0         1   5       1        45.0   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width     ram  sc_h  sc_w  \
0     

### **No 2**

a. Pisahkan bagian atribut prediktor dengan label data menjadi dua variabel terpisah



In [5]:
# Memisahkan atribut prediktor dan atribut label
x = data.drop(columns=["price_range"])
y = data["price_range"]

In [6]:
# Menampilkan hasil dari pemisahan atribut prediktor dan atribut label
print("Atribut Prediktor (Fitur):")
print(x.head())

print("\nAtribut Label:")
print(y.head())

Atribut Prediktor (Fitur):
   battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0          842.0     0          2.2         0   1       0         7.0    0.6   
1         1021.0     1          0.5         1   0       1        53.0    0.7   
2          563.0     1          0.5         1   2       1        41.0    0.9   
3          615.0     1          2.5         0   0       0        10.0    0.8   
4         1821.0     1          1.2         0  13       1        44.0    0.6   

   mobile_wt  n_cores  pc  px_height  px_width     ram  sc_h  sc_w  talk_time  \
0      188.0        2   2         20       756     NaN     9     7         19   
1      136.0        3   6        905      1988  2631.0    17     3          7   
2      145.0        5   6       1263      1716  2603.0    11     2          9   
3      131.0        6   9       1216      1786  2769.0    16     8         11   
4      141.0        2  14       1208      1212  1411.0     8     2         15   

   th

b. Gunakan SimpleImputer untuk menangani *missing values*, dengan nilai median dari atribut data sebagai strategi pengisian nilai

In [7]:
# Handling Missing Values
imputer = SimpleImputer(strategy="median")

x_imputer = imputer.fit_transform(x)
x_imputer_df = pd.DataFrame(x_imputer, columns=x.columns)

In [9]:
# Menampilkan atribut prediktor setelah pengisian missing values
print("Atribut Prediktor setelah Pengisian Missing Values:")
print(x_imputer_df.head())

Atribut Prediktor setelah Pengisian Missing Values:
   battery_power  blue  clock_speed  dual_sim    fc  four_g  int_memory  \
0          842.0   0.0          2.2       0.0   1.0     0.0         7.0   
1         1021.0   1.0          0.5       1.0   0.0     1.0        53.0   
2          563.0   1.0          0.5       1.0   2.0     1.0        41.0   
3          615.0   1.0          2.5       0.0   0.0     0.0        10.0   
4         1821.0   1.0          1.2       0.0  13.0     1.0        44.0   

   m_dep  mobile_wt  n_cores    pc  px_height  px_width     ram  sc_h  sc_w  \
0    0.6      188.0      2.0   2.0       20.0     756.0  2146.5   9.0   7.0   
1    0.7      136.0      3.0   6.0      905.0    1988.0  2631.0  17.0   3.0   
2    0.9      145.0      5.0   6.0     1263.0    1716.0  2603.0  11.0   2.0   
3    0.8      131.0      6.0   9.0     1216.0    1786.0  2769.0  16.0   8.0   
4    0.6      141.0      2.0  14.0     1208.0    1212.0  1411.0   8.0   2.0   

   talk_time  three_g 

c. Terapkan MinMaxScaler atau **StandardScaler** untuk mengubah nilai atribut prediktor, agar nilai dari masing-masing atribut menjadi seragam

In [11]:
# Scaling Data menggunakan StandardScaler
scaler = StandardScaler()
x_scaler = scaler.fit_transform(x_imputer_df)
x_scaler_df = pd.DataFrame(x_scaler, columns=x.columns)

In [12]:
# Menampilkan hasil dari atribut prediktor setelah scaling data
print("Atribut Prediktor setelah Scaling:")
print(x_scaler_df.head())

Atribut Prediktor setelah Scaling:
   battery_power      blue  clock_speed  dual_sim        fc    four_g  \
0      -0.902700 -0.990050     0.830779 -1.019184 -0.762495 -1.043966   
1      -0.494459  1.010051    -1.253064  0.981177 -0.992890  0.957886   
2      -1.539009  1.010051    -1.253064  0.981177 -0.532099  0.957886   
3      -1.420414  1.010051     1.198517 -1.019184 -0.992890 -1.043966   
4       1.330083  1.010051    -0.395011 -1.019184  2.002254  0.957886   

   int_memory     m_dep  mobile_wt   n_cores        pc  px_height  px_width  \
0   -1.381584  0.340740   1.349561 -1.101971 -1.305750  -1.408949 -1.146784   
1    1.161752  0.687548  -0.123125 -0.664768 -0.645989   0.585778  1.704465   
2    0.498273  1.381165   0.131763  0.209639 -0.645989   1.392684  1.074968   
3   -1.215715  1.034357  -0.264729  0.646842 -0.151168   1.286750  1.236971   
4    0.664142  0.340740   0.018479 -1.101971  0.673534   1.268718 -0.091452   

        ram      sc_h      sc_w  talk_time   three_

d. Tampilkan statistik deskriptif dari atribut data sebelum dan setelah dilakukan pengisian missing values dan standarisasi

In [13]:
# Menampilkan Statistik Deskriptif
print("Statistik deskriptif sebelum pengisian missing values:")
print(x.describe())

print("\nStatistik deskriptif setelah pengisian missing values dan standarisasi:")
print(x_scaler_df.describe())

Statistik deskriptif sebelum pengisian missing values:
       battery_power       blue  clock_speed     dual_sim           fc  \
count    1990.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1237.867839     0.4950     1.522250     0.509500     4.309500   
std       439.676025     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       850.250000     0.0000     0.700000     0.000000     1.000000   
50%      1225.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.000000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  \
count  2000.000000  1990.000000  2000.000000  1990.000000  2000.000000   
mean      0.521500    31.987940     0.501750   140.344221     4.520500   
std       0.499662    18.136427     0.288416    35.40711

### **No 3**

a. gunakan salah satu algoritma untuk membangun model klasifikasi

Menggunakan Algoritma ***Decision Tree***

---



b. gunakan metode holdout untuk membagi keseluruhan dataset, data training 80% data testing 20%

In [16]:
# Memisahkan atribut prediktor (X_scaled) dari label data (y)
X_train, X_test, y_train, y_test = train_test_split(x_scaler, y, test_size=0.2, random_state=42)

In [17]:
# Inisialisasi model Decision Tree
model = DecisionTreeClassifier(random_state=42)

# Latih model pada data pelatihan
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [18]:
#Melakukan prediksi pada data pengujian
y_pred = model.predict(X_test)

c. tampilkan confussion matrix dan akurasi dari model klasifikasi

In [19]:
  # Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)

# Menampilkan confusion matrix
print("Confusion Matrix:")
print(cm)

# Menampilkan akurasi
print("Akurasi: {:.2f}%".format(accuracy * 100))

Confusion Matrix:
[[90 15  0  0]
 [ 5 74 12  0]
 [ 0 16 64 12]
 [ 0  0 13 99]]
Akurasi: 81.75%


### Soal Nomor 4

Menggunakan Algoritma ***K-Means***

---



In [21]:
# Inisialisasi model K-Means
n_clusters = 5
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)

# Latih model K-Means
kmeans.fit(x_scaler)

KMeans(n_clusters=5, n_init=10, random_state=42)

b. Tampilkan silhouette score dari model clustering

In [23]:
# Menampilkan Silhouette Coefficients
kmeans_kwargs = {"init": "random", "n_init": 10}
silhouette_coefficients = []

for k in range(2, 21):
    kmeans = KMeans(n_clusters=k, **kmeans_kwargs)
    kmeans.fit(x_scaler_df)
    score = silhouette_score(x_scaler_df, kmeans.labels_)
    silhouette_coefficients.append(score)
    print(f"Silhouette Score for {k} clusters: {score}")

print("Silhouette Score:", score)

Silhouette Score for 2 clusters: 0.067724062611456
Silhouette Score for 3 clusters: 0.06558756179253894
Silhouette Score for 4 clusters: 0.05828182955390204
Silhouette Score for 5 clusters: 0.054235112525648006
Silhouette Score for 6 clusters: 0.04736299405990943
Silhouette Score for 7 clusters: 0.05014937336872782
Silhouette Score for 8 clusters: 0.04679215161783967
Silhouette Score for 9 clusters: 0.04783951678906953
Silhouette Score for 10 clusters: 0.04655270918688458
Silhouette Score for 11 clusters: 0.045066642614394456
Silhouette Score for 12 clusters: 0.04446824097830299
Silhouette Score for 13 clusters: 0.044868978245562345
Silhouette Score for 14 clusters: 0.045721025256733314
Silhouette Score for 15 clusters: 0.04447743271935947
Silhouette Score for 16 clusters: 0.04408613245221318
Silhouette Score for 17 clusters: 0.044692538650023185
Silhouette Score for 18 clusters: 0.04503718083302409
Silhouette Score for 19 clusters: 0.04641407848257801
Silhouette Score for 20 clusters: